sudo: required
services:
  - docker

before install:
  - docker build -t inomag/laughing-eureka -f Dockerfile.dev .

script:
  - docker run -e CI=true inomag/laughing-eureka npm run test -- --coverage
